# command line: main_cigcn.py --config configs/cigcn_1215_jnt_t.yaml

batch_size: 64
batch_size_test: 32
case: 0
config: configs/cigcn_1215_jnt_t.yaml
dataset: NTU
debug: false
device: 0
h5_npz: 1
judge_GPU_set: 0
judge_binary: 0
judge_dataMode: 2
judge_dataSource: cs
judge_dataType: 0
judge_dataloader: sgn
judge_inputDataShape: 3
judge_rot: 1
lr: 0.001
lr_factor: 0.1
max_epochs: 120
milestones:
- 60
- 90
- 110
mmap: false
monitor: val_acc
network: CIGCN
network_label: 0
num_classes: 60
print_freq: 20
result_dir: cigcn_debug_cs_1215_jnt_t2
resume: 0
seg: 20
split_csub: false
start_epoch: 0
test_feeder_args: {}
test_feeder_paths: {}
test_group: 20
test_loader: null
train: 1
train_feeder_args: {}
train_feeder_paths: {}
train_loader: null
val_loader: null
weight_decay: 0.0001
with_att: true
with_block_tcn: true
with_gcn_frm: true
with_gcn_tcn_para: true
workers: 16
